version: '2'
services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306"


  server:
    container_name: openapi-backend
    image: openapi:1.0.0
    build:
        context: .
        dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
        - 3000:3000
    networks:
        - nesjs-network
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
       db:
          condition: service_healthy
