version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "openapp"
    container_name: db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  server:
    container_name: openapi-backend
    image: openapi:1.0.0
    build: .
    command: npm run start
    ports:
        - "5000:3000"
    restart: unless-stopped
    depends_on:
        - db
#docker run --name openapp_db -e MYSQL_ROOT_PASSWORD="password" -e MYSQL_DATABASE="openapp"  -p 3306:3306 --platform linux/x86_64 mysql
